import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { clientsClaim } from 'workbox-core';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache images with a CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'zengalla-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache Google Fonts with StaleWhileRevalidate
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts',
  })
);

// Handle SKIP_WAITING message
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Immediately claim clients
clientsClaim();




// Handle Push Notifications
self.addEventListener('push', (event) => {
  if (!event.data) return;

  const data = event.data.json();
  const options = {
    body: data.body,
    icon: '/logo.svg',
    badge: '/favicon.svg',
    vibrate: [200, 100, 200, 100, 200, 100, 200],
    data: {
      url: data.url || '/',
      orderId: data.orderId
    },
    actions: data.actions || [],
    tag: data.tag || 'general-notification',
    renotify: true,
    requireInteraction: data.priority === 'high'
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
  const notification = event.notification;
  const action = event.action;

  notification.close();

  if (action === 'accept') {
    // Logic to accept order via API could go here, 
    // but usually we just redirect to the app
    event.waitUntil(
      clients.openWindow(`${notification.data.url}?action=accept&orderId=${notification.data.orderId}`)
    );
  } else {
    event.waitUntil(
      clients.openWindow(notification.data.url)
    );
  }
});
