/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Notifications
self.addEventListener('push', (event) => {
  if (!event.data) return;

  const data = event.data.json();
  const options = {
    body: data.body,
    icon: '/logo.png',
    badge: '/favicon.svg',
    vibrate: [200, 100, 200, 100, 200, 100, 200],
    data: {
      url: data.url || '/',
      orderId: data.orderId
    },
    actions: data.actions || [],
    tag: data.tag || 'general-notification',
    renotify: true,
    requireInteraction: data.priority === 'high'
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
  const notification = event.notification;
  const action = event.action;

  notification.close();

  if (action === 'accept') {
    // Logic to accept order via API could go here, 
    // but usually we just redirect to the app
    event.waitUntil(
      clients.openWindow(`${notification.data.url}?action=accept&orderId=${notification.data.orderId}`)
    );
  } else {
    event.waitUntil(
      clients.openWindow(notification.data.url)
    );
  }
});
